#!/usr/local/bin/perl
#Program: grup
#Author: Michael Fisk (mfisk@nmt.edu)
#Date: originally 10-13-94
#Language: Perl
# $Id$

#Expand a YP netgroup, recursively, and apply a command to all machines in it

$DefaultCmd = "ping %mx 1";
$MAXPROCS = 15;

if (! @ARGV) {
    print <<EOM;
Usage: $0 [-Option] [[-h hostname] ...] [netgroup] [-ExecOption commands]

Valid "Options" are as follows.  
Only enough of the option name to make it unamiguous is required:
\t-fail   \tonly show output from commands that fail
\t-first  \tshows the first up machine that returns
\t-fork   \tfork each command instead of running them sequentially
\t-hostname\tspecifies a hostname to use
\t-noheader\tdon't print "Checking:" header
\t-nosummary\tdon't print final summary
\t-quiet  \tonly returns the output from the child processes
\t-summary\tonly returns summary information 
\t-succeed\tonly show output from commands that succeed
\t-timeout\tAbort rsh commands after so many seconds (default 60)

The following "ExecOptions" must be after the netgroup and/or hostnames:
\t-e[xec]   \texecutes an sh command for each machine with any
\t\t\treference of %mx translated to the remote machine name
\t-r[sh]    \tis the same as -e with "rsh %mx" prepended
\t-p[erl]   \tis the same as -e but the command is evaluated as Perl 

\tThe default command if no -e is given is:\tping %mx 1
EOM
    exit;
}

$SIG{ALRM} = 'AlrmHandler';
$Timeout = 60;
$Header = 1;
$Summary = 1;
while($_ = shift) {
    if (/^-fi/) {
	$First = 1; $Header = 0; $Summary = 0;
    } elsif (/^-fa/) {
	$FailsOnly = 1;
    } elsif (/^-f/) {
	$DoFork = 1;
    } elsif (/^-e/) {
	$ExecCmd = join(" ",@ARGV);
	@ARGV = ();
    } elsif (/^-r/) {
	$ExecCmd = "rsh %mx " . join(" ",@ARGV);
	$CheckPort = 514;
	@ARGV = ();
    } elsif (/^-p/) {
	$PerlCmd = 1;
	$ExecCmd = join(" ",@ARGV);
	@ARGV = ();
    } elsif (/^-noh/) {
	$Header = 0;
    } elsif (/^-nos/) {
	$Summary = 0;
    } elsif (/^-h/) {
	push(@mxlist,shift);
    } elsif (/^-q/) {
        $quiet = 1; $Header = 0; $Summary = 0;
    } elsif (/^-suc/) {
	$SuccessOnly = 1;
    } elsif (/^-s/) {
	$SummaryOnly = 1;
	$quiet = 1;
    } elsif (/^-t/) {
	$Timeout = shift;
    } elsif (/^-/) {
	print stderr "Unknown or ambiguous option `$_'!\n";
    } else {
	unshift(@groups,$_);
    }
}


#Parse a netgroup
while ($group=shift(@groups)) {
    $yplist = `ypmatch $group netgroup`;
    @list = split(/\s+/,$yplist);
    foreach $mx (@list) {
	if ($mx =~ /^\(/) {
	    $mx = (split(/[\(,]/,$mx))[1];
	    if ( $mx ) { push(@mxlist,$mx); }
	} else {
	    push(@groups,$mx);
	}
    }	
}

if (! @mxlist) { 
    print "No machines in netgroup \"$group\"\n"; 
    exit; 
}
print "Checking: @mxlist\n\n" if $Header;


$upcount = $downcount = 0;

if ($DoFork) {
    while ($mx = shift(@mxlist)) {
	unshift(@smallist,$mx);
	if ($#smallist == $MAXPROCS) {
	    &CheckGroup(@smallist);
	    @smallist = ();
	}
    }
    &CheckGroup(@smallist);
} else {
    &CheckGroup(@mxlist);
}

exit if ! $Summary;
 
print "\n$upcount Succeeded; $downcount Failed; ";
print $#mxlist+1 . " Machines\n";
exit;

sub DoCmd {
    local($mx) = shift;
    local($execcmd);
    local($ping);
    local($exit) = 0;

    $execcmd = $ExecCmd || $DefaultCmd;
    $execcmd =~ s|%mx|$mx|g;
    if ($PerlCmd) {
	print "$mx:\t" unless $quiet;
	$exit = ! eval $execcmd;
	print "\n";
    } else { 
	if ($CheckPort) {
	    if ($ping = &SocketTest($mx,$CheckPort)) {
		              #Host not answering
		$? = 1 << 8;
	    } else {
		              #Host should be up.
		if ($ChildPid = open(pingcmd,"-|")) {
		    $ping = '';
		    alarm($Timeout);
		    while(<pingcmd>) { 
			$ping .= $_; 
		    }
		    alarm(0);
		} elsif (defined($ChildPid)) {
		    close(STDERR);
		    open(STDERR,">&STDOUT");
		    exec "$execcmd" || die "exec: $!";
		} else {
		    print stderr "fork: $!\n";
		}
		$ChildPid = 0;
#		$ping = `$execcmd 2>&1`;
		alarm(0);
	    }
	} else {
	    $ping = `$execcmd 2>&1`;
	}
	$exit = $? >> 8;
	if (! $ExecCmd) {
	    $ping =~ s|$mx||g;
	    $ping =~ s|is ||g;
	    $ping =~ s|from ||g;
	}
	if (($FailsOnly && $?) || ($SuccessOnly && !$?) ||
	    (! ($FailsOnly || $SuccessOnly))) {
	    print "$mx:\t" unless $quiet;
	    print $ping unless $SummaryOnly;
	}
    }
    return $exit;
}

sub CheckGroup {
    local(@mxlist) = @_;
    local($notdone);

    $notdone = $#mxlist+1;
    @pids = ();
    $mxnum = 0;

#Spawn a process to check each machine
    foreach $mx (@mxlist) {
	if ($DoFork) {
	    $pids[$mxnum] = fork;	
	    {
		if ($pids[$mxnum] >= 0) { # Successful fork
		    if (! $pids[$mxnum]) { # Child
			exit(&DoCmd($mx));
		    }		       
		} else {		# Unsuccessful fork
		    warn "Retrying $mx: fork: $!\n";
		    sleep 3;
		    redo;
		}
	    }
	    $mxnum++;
	} else {
	    if (! &DoCmd($mx)) {
		$upcount++;
		exit if $First;
	    } else {
		$downcount++;
	    }
	}
    }			      

    return unless $DoFork;

#Check output of child processes
    while ( $notdone ) {
	for ($i=0; $i <= $#mxlist; $i++) {
	    if ( @pids[$i] ) {
		$wp = waitpid(@pids[$i],1);
		if ( $wp > 0 ) { 
		    $? = $? >> 8;
		    if (! $? ) {
			$upcount++;
		    } else {
			$downcount++;
		    }
		    @pids[$i] = 0;
		    $notdone--;
		}
	    }
	}
    }
}

sub SocketTest {
    local($Node) = shift;
    local($Port) = shift;
    local($sock) = 'tmpS';

    $sockaddr = 'S n a4 x8';
    $AF_INET = 2;
    $SOCK_STREAM = 1;

    ($Name, $Alias, $Proto) = getprotobyname('tcp');
    ($Name, $Alias, $Port)  = getservbyname($Port, 'tcp') 
        unless $Port =~ /^\d+$/;
    ($Name, $Alias, $Type, $Len, $ThisAddr) = gethostbyname($Host);
    ($Name, $Alias, $Type, $Len, $ThatAddr) = gethostbyname($Node);
    if (! $ThatAddr) { return("Unknown host: $Node\n"); }

    $This = pack( $sockaddr, $AF_INET, 0, $ThisAddr);
    $That = pack( $sockaddr, $AF_INET, $Port, $ThatAddr);

    if (! socket($sock, $AF_INET, $SOCK_STREAM, $Proto)) { 
        return("socket: $!\n"); 
    }
    if (! bind($sock, $This)) { return("bind: $!"); }

    alarm(1);
    $GlobalAlarmSocket = $sock;
    if (! connect($sock,$That)) { 
	alarm(0);
	close($sock);
	return("No response\n");
    } else {
	alarm(0);
	close($sock);
	return(undef);
    }
}

sub AlrmHandler {
    close($GlobalAlarmSocket); #Linux sigreturn() resumes connect()
    if ($ChildPid) { 
	kill(INT,$ChildPid) || die "kill $!";
	$? = 1 << 8;
	$ping .= "Timeout\n";
    }
}

sub Wall {
    while( ($no,$handle) = each(%FH)) {
	if ($handle eq 'S0') { next; }
	print $handle "@_";
    }
}

sub CloseAndExit {
    while( ($no,$handle) = each(%FH)) {
	print $handle "Server going down.\n";
	shutdown($FH{$no},2) || warn "shutdown: $!";
	close $handle;
#	print stderr "Closed $handle\n";
    }
    exit;
}
